server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client:
            RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: "*aM-T55vgRyswu"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: "http://localhost:9000"

external:
  api:
    go:
      base-url: https://gorest.co.in/public/v2
      posts-endpoint: /posts
      users-endpoint: /users
      comments-endpoint: /comments